spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;databaseName=rest_with_spring_boot_udemy
        username: sa
        password: admin123!

    jackson:
        default-property-inclusion: NON_NULL

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect

        hibernate:
            ddl-auto: update
        show-sql: false

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB

flyway:
    url: jdbc:sqlserver://localhost;databaseName=rest_with_spring_boot_udemy
    schemas: dbo
    user: sa
    password: admin123!

file:
    upload-dir: /Programacao/Spring/UdemySpringBoot/UploadDir
